version: "3.9"  # optional since v1.27.0

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./docker/app/.env
    ports:
      - 5000:5000
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    env_file:
      - ./docker/mysql/.env
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/mysql --user=$MYSQL_DB_USER --password=$MYSQL_DB_PASSWORD --execute 'SHOW DATABASES';"]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 3s
